# -*- coding: utf-8 -*-
# Generated by Django 1.10.1 on 2016-09-09 12:17
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('multitoken', '0002_auto_20160909_0303'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='token',
            unique_together=set([('user', 'client')]),
        ),
    ]
